sed -i -- 's/\bRUECKGABE\b/RETURN/g' Rule*.txt
sed -i -- 's/\bREIHE\b/SEQUENCE/g' Rule*.txt
sed -i -- 's/\bIN\b/IN/g' Rule*.txt
sed -i -- 's/\bMATERIAL\b/DATASET/g' Rule*.txt
sed -i -- 's/\bFUNKTION\b/FUNCTION/g' Rule*.txt
sed -i -- 's/\bABSOLUTWERT\b/ABSOLUTEVALUE/g' Rule*.txt
sed -i -- 's/\bJEDES\b/EVERY/g' Rule*.txt
sed -i -- 's/\bNICHT\b/NOT/g' Rule*.txt
sed -i -- 's/\bSONST\b/ELSE/g' Rule*.txt
sed -i -- 's/\bENDE\b/END/g' Rule*.txt
sed -i -- 's/\bUND\b/AND/g' Rule*.txt
sed -i -- 's/\bODER\b/OR/g' Rule*.txt
sed -i -- 's/\bWENN\b/IF/g' Rule*.txt
sed -i -- 's/\bDANN\b/THEN/g' Rule*.txt
sed -i -- 's/\bFUER\b/FOR/g' Rule*.txt
sed -i -- 's/\bPRUEFE\b/CHECK/g' Rule*.txt
sed -i -- 's/\bLEER\b/EMPTY/g' Rule*.txt
sed -i -- 's/\bWERTLAENGE\b/LENGTH/g' Rule*.txt
sed -i -- 's/\bTEIL\b/PART/g' Rule*.txt
sed -i -- 's/\bVAR\b/DECLARE/g' Rule*.txt
sed -i -- 's/\bFALSCH\b/FALSE/g' Rule*.txt
sed -i -- 's/\bWIEDERHOLE\b/LOOP/g' Rule*.txt
sed -i -- 's/\bBIS\b/UNTIL/g' Rule*.txt
sed -i -- 's/\brueck\b/rc/g' Rule*.txt
sed -i -- 's/\bhf_/tmp_/g' Rule*.txt
